姓名：Greetings

关于：[ pull_request_target，问题]

职位：
  问候语：
    运行：ubuntu-latest
    权限：
      问题：write
      拉取请求：write
    步骤：
    -用途：actions/first-interaction@v1
      和：
        回购令牌：${ { secrets.GITHUB_TOKEN } }
        issues-message : "将在用户的第一个问题上显示的消息"
        pr-message ：“将在用户的第一个拉取请求中显示的消息”
